/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TChoButtonKind, } from "./components/inputs/button/model";
export namespace Components {
    interface ChoButton {
        "disabled"?: boolean;
        "kind"?: TChoButtonKind;
    }
    interface ChoList {
    }
    interface ChoListItem {
    }
    interface ChoRouter {
    }
}
declare global {
    interface HTMLChoButtonElement extends Components.ChoButton, HTMLStencilElement {
    }
    var HTMLChoButtonElement: {
        prototype: HTMLChoButtonElement;
        new (): HTMLChoButtonElement;
    };
    interface HTMLChoListElement extends Components.ChoList, HTMLStencilElement {
    }
    var HTMLChoListElement: {
        prototype: HTMLChoListElement;
        new (): HTMLChoListElement;
    };
    interface HTMLChoListItemElement extends Components.ChoListItem, HTMLStencilElement {
    }
    var HTMLChoListItemElement: {
        prototype: HTMLChoListItemElement;
        new (): HTMLChoListItemElement;
    };
    interface HTMLChoRouterElement extends Components.ChoRouter, HTMLStencilElement {
    }
    var HTMLChoRouterElement: {
        prototype: HTMLChoRouterElement;
        new (): HTMLChoRouterElement;
    };
    interface HTMLElementTagNameMap {
        "cho-button": HTMLChoButtonElement;
        "cho-list": HTMLChoListElement;
        "cho-list-item": HTMLChoListItemElement;
        "cho-router": HTMLChoRouterElement;
    }
}
declare namespace LocalJSX {
    interface ChoButton {
        "disabled"?: boolean;
        "kind"?: TChoButtonKind;
    }
    interface ChoList {
    }
    interface ChoListItem {
    }
    interface ChoRouter {
    }
    interface IntrinsicElements {
        "cho-button": ChoButton;
        "cho-list": ChoList;
        "cho-list-item": ChoListItem;
        "cho-router": ChoRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cho-button": LocalJSX.ChoButton & JSXBase.HTMLAttributes<HTMLChoButtonElement>;
            "cho-list": LocalJSX.ChoList & JSXBase.HTMLAttributes<HTMLChoListElement>;
            "cho-list-item": LocalJSX.ChoListItem & JSXBase.HTMLAttributes<HTMLChoListItemElement>;
            "cho-router": LocalJSX.ChoRouter & JSXBase.HTMLAttributes<HTMLChoRouterElement>;
        }
    }
}
