name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Install Packages
        run: npm install && npm run lerna -- bootstrap

      - name: Run build
        run: npm run lerna -- run build

      - name: Run tests
        run: npm run lerna -- run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './packages/cho-components/coverage/lcov.info'
          base-path: 'packages/cho-components'
