name: develop

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true

      - name: Install Packages
        run: npm install && npm run lerna -- bootstrap

      - name: Run build
        run: npm run lerna -- run build

      - name: Run tests
        run: npm run lerna -- run test
